### ISSUE TITLE
Wrong results when both arguments have trailing slashes

### ISSUE THREAD

**Issue by jessaustin** [js-n/url-relative#1]
This is wrong:

``` javascript
> require('url-relative')('/a/', '/b/c/');
'b/c/'
```

Clearly the right answer would be `'../b/c/'`. If we're in the `/a/` directory, we have to back out of it before we can go into a top-level directory like `/b/`.

**Comment by jden** [comment]
Thanks for reporting this! I don't have the time right now to actively maintain this module, but I'd be happy to review and merge a pull request. If anyone is interested in taking over maintainership of this module, I'm happy to add admins under the [Open Open Source](http://openopensource.org/) model. In the mean time, I've added the **bug** label to this issue to help raise visibility for others coming across this repo.

**Comment by mojavelinux** [comment]
PR sent!

I added tests for every case to ensure this change is correct. Starting with a directory index path is a special case, so we have to test each scenario again.
